baseURL = "https://www.hiroakit.com"
languageCode = "ja-JP"
title = "Hiroaki ENDOH"
theme = "kiss"
googleAnalytics = "UA-10216886-3"
Paginate = 5

# Syntax Highlight
# https://gohugo.io/content-management/syntax-highlighting/
pygmentsUseClasses = true
pygmentsCodefences = true
# pygmentsoptions = "linenos=inline"

[permalinks]
  post = "/:year/:month/:filename/"
  
[params]

[params.info]
  homeTitle = "Hiroaki ENDOH"
  enableSocial = true

[params.social]
  twitter = "hiroakit"

[params.assets]
  customCSS = ["custom.css"]
