#+TITLE: 二重入力されるFirefoxの検索バー
#+DATE: 2008-11-26T08:35:00+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<p>僕はネットを見るときにはFirefoxをよく使うのですが、そのFirefoxでいつもとはおかしい挙動が見受けられるようになりました。つい最近のことです。</p>
<h4>現象</h4>
<p>Firefoxの検索バーに入力した日本語が、確定時に繰り返し入力される</p>
<ul>
<li>アドビ&rarr; アドビアドビ</li>
<p>ただ、検索は アドビアドビ でなく、 アドビで行われます。<br /> そして、この現象は英数字の入力の場合には起きません。</p>
</ul>
<ul>
<li>Adobe &rarr; Adobe</li>
<p>ただ、英数字の入力の場合はこの現象が起きません。</p>
</ul>
<h4>解決策</h4>
<p>検索すると、Mozilla Japan の方ですでに記事として上がっていました。</p>
<ul>
<li><a href="http://mozilla.jp/support/firefox/kb/002577">ナレッジベース: 日本語入力時に、変換した文字列が繰り返し入力される</a></li>
</ul>
<blockquote>
<p>お使いのコンピュータにインストールされている「Adware.NDotNet (NewDotNet)」が原因です。</p>
</blockquote>
<p>&nbsp;</p>
<p>原因が割とストレートに書いてありました。<br /> ひとまず、プログラムの追加と削除を確認してからウィルス検索をしてみる。</p>
<p>しかし、「Adware.NDotNet (NewDotNet)」はリストに載っておらず、<br /> その代わりに身に覚えのない「OneStepSearch」がリストに載っていました。</p>
<p>ひとまず、消します。</p>
<h4>結果</h4>
<p>問題となっていた、二重に入力される現象は起こらなくなりました。<br /> なお、同じような症状に見舞われていた方がいらっしゃいました。</p>
<ul>
<li><a href="http://plaza.rakuten.co.jp/satoyaji/diary/200810240000/">IE完治です！</a></li>
</ul>
<blockquote>
<p>どんな不具合かというと、FireFoxの検索バーに日本語入力すると二重に入力されるという症状でした。　例えば"福山"と入力すると"福山福山"になってしまいます。　この病気も使いづらかったので、治って良かったです。</p>
</blockquote>
