#+TITLE: エレベータの「閉」は要らないのではないだろうか
#+DATE: 2009-12-03T12:54:57+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

この前、渋谷にあるApple Storeへ行ってきました。<!--more-->

決して<a href="http://www.hiroakit.com/blog/archives/1267">大量のApple製品</a>を買ったわけではありません。近くのお店へ寄ったのでついでにApple Storeに入っただけです。そして、店内にあるエレベータにちょっと興味があったので乗りました。

興味があった部分は乗ったエレベータに「閉」ボタンがあるかどうかです。渋谷店のエレベータにはそのボタンがあったのですが、同系列店のApple Store 銀座店では「閉」ボタンがエレベータ内に存在していないのです。

日本国内のエレベータの大半は「閉」ボタンがあると思うので、「閉」ボタンが無いのはごくまれなケースとして捉えることが出来ます。ただ、「閉」ボタンが無いのを見かけてしまうと疑問を抱くことがあるのです。例えば、エレベータのドアが何秒で自動に閉まるのかと時間を測ってみると大体約4～5秒です。「閉」ボタンはこの時間を操作するために付けたのだろうかと。恐らく違う理由があると思うのですが、それならば実際の理由は何なのだろうかと疑問を持ちます。

「閉」ボタンがあって困ることは、「開」ボタンと押し間違えてエレベータに乗ろうとした人をドアで挟んでしまい気まずい空気がその場に流れることです。普通の人はないそうですが本当に僕だけだろうか。その逆にドアに挟まれたことも普通の人はないそうですが本当にそうだろうか。「ただ単にそういうことがあったことを恥ずかしくて言えないからそのまんまにして隠しているだけじゃないの」とユーモアたっぷりに思ってしまうのは僕だけだろうか。

ちなみに僕はしょっちゅう挟まれ挟んでしまうこと、あります。

<strong>References</strong>
<ul>
<li><a href="http://blog.kishin-design.com/?eid=1024110">kishin Design | Macとデザインと美しいモノのブログ | エレベータの「閉」は不用</a></li>
<li><a href="http://yadorigi.seesaa.net/article/20325446.html">やどりぎ@NET: アップルストアのエレベータから学ぶ良いデザインの原則</a></li>
<li><a href="http://pingmag.jp/J/2006/12/06/logan-production-company-making-people-dance/">PingMag - 東京発 「デザイン＆ものづくり」 マガジン » Archive » 世界中を踊らせる制作会社、ローガン</a></li>
</ul>

