#+TITLE: C言語入門してみた　Part1
#+DATE: 2009-04-19T12:25:30+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4>借りてきた: 新Ｃ言語入門　スーパービギナー編</h4>
<p>大学で『<a href="http://www.amazon.co.jp/gp/product/4797325631?ie=UTF8&amp;tag=hiroakit-22&amp;linkCode=as2&amp;camp=247&amp;creative=1211&amp;creativeASIN=4797325631">新C言語入門 スーパービギナー編 (C言語実用マスターシリーズ)</a>』という本を借りてきました。どこから勉強すればいいのか良くわからなかったので、とりあえず簡単そうなものから手をつけていくことにしました。</p>
<p>―というのも、LiquidのPixieのコンパイルがうまくいかないところからC言語の勉強をしようと思ったので、メインはC言語を習得することではなくコンパイルを成功させることです。(( このまえ頂いた@hさんのアドバイスを元にやってみましたが、まだちょっと何かが足りないみたいなので続行中です。</p>
<p>さて、ペラペラと読んでみると、本の最初のほうに見ているとC言語を開発した理由が書いてありました。1972年ごろのアメリカ「ベル研究所」でUNIXを開発するためだったらしいです。そんな経緯があったなんて初めて知りました。</p>
<h4>目次をチェックしてみた</h4>
<pre>Chapter1 Ｃとはどのような言語か<br />Chapter2 どうやってプログラムを作るのか<br />Chapter3 Ｃプログラミングの８つのステップ<br />Chapter4 まず何か出力させてみよう（出力）<br />Chapter5 データを置いておく場所を確保しよう（変数）<br />Chapter6 数字の計算をしてみよう（演算）<br />Chapter7 データの入出力を覚えよう（入力と出力）<br />Chapter8 ある条件のときだけ処理させよう（条件文）<br />Chapter9 何度も繰り返して処理させよう（繰り返し文）<br />Chapter10 よく使う処理は関数にしよう（関数）<br />Chapter11 標準ライブラリ関数を使おう<br />Chapter12 ファイル処理も覚えよう（ファイル処理）<br />Chapter13 その他のＣに機能をみてみよう（Ｃ言語の全体像）<br />Chapter14 さらなる向上のために<br />Appendix Visual　C++を利用してCコンパイラを使う方法</pre>
<p>全て読んでいくのは賢そうに思えないので、今は必要そうなところだけ読んでいこうと思います。後々必要になったらそのときに補っていく方向でいこうかなと。</p>
<p>じゃあ、どこから読んでいけばいこうかというところに悩んで、とりあえずChapter5からChapter9までを読み進めていこうと思います。(( なんか全部読んでいくのとあまり変わらない気がするけどｗｗ</p>
<h4>Chapter5</h4>
<p>変数のことが書かれています。</p>
<h5>データ型</h5>
<ul>
<li>char <br />文字型(-128?127)</li>
<li>int <br />整数型(-2147483648?2147483647)</li>
<li>double<br />倍精度浮動小数点数(10の-308乗から10の308乗)</li>
</ul>
<h5>printf()</h5>
<ul>
<li>%o<br />8進数で出力する</li>
<li>%d<br />10進数で出力する</li>
<li>%x<br />16進数で出力する(小文字)</li>
<li>%X<br />16進数で出力する(大文字)</li>
<li>%f<br />浮動小数点数として出力する</li>
<li>%C<br />文字として出力する</li>
<li>%S<br />文字列として出力する</li>
</ul>
<h4>Chapter6</h4>
<p>加減乗除のことについて書いてあります。+, -, *, /, % で各々表現していくみたい。それからインクリメント演算子とデクリメント演算子って言葉が出てきます。（大学でJavaの講義が必修であるんだけども、たぶん触れているはずｗｗ）</p>
<p>インクリメント演算子が増加のことで、デクリメント演算子が減少のこと。<br />++a; といった表現の仕方をするようです。(( そういえば、この形は良く見ますね。</p>
<h4>Chapter7</h4>
<p>データの入出力に関して書いてあります。キーボードから入力されたデータをどうするかってことかな。</p>
<ul>
<li>scanf()関数<br />1文字入力を行うためのもの<br />(新Ｃ言語入門　ビギナー編でさらに詳しいことが書いてあるみたい)</li>
<li>getchar()関数<br />1文字入力を行うためのもの</li>
<li>putchar()関数<br />1文字を画面に出力するもの</li>
<li>gets()関数<br />キーボードから文字列を入力するもの</li>
<li>puts()関数<br />文字列を出力するためのもの</li>
</ul>
<h4>Chapter8からChapter11まで</h4>
<p>今日はここまでにして、Chapter8からChapter9はゆっくりと読んでいこうと思います。<br />ソースコードも書きたいところだけど、エントリシートを書かないといけないことを思い出した(笑</p>
