#+TITLE: "個性的な発想を掴むために"
#+DATE: 2009-03-10T08:00:00+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4><span>多くの段階を踏む</span></h4>
<p>以前、<a href="http://www.hiroakit.com/blog/2009/03/post_37.html" target="_blank">オリジナリティの追求の仕方がここにある</a>という記事を書きました。その記事での結論は、時間的な理由や、まだまだわからない部分があって、<span>"個性的な発想を掴むためには多くの段階を踏む必要がある"</span>で話を終わらせました。</p>
<p>その後、多くの段階を踏むというのはどういうことを指すのだろうか、と考えました。<br />(結局のところ、結論らしいものは何一つ得ていません)</p>
<h4>人生のログファイル</h4>
<p><a href="http://d.hatena.ne.jp/gothedistance/" target="_blank">gothedistanceさん</a>が<a href="http://d.hatena.ne.jp/gothedistance/20090223/1235362716" target="_blank">オリジナリティのつくりかた</a>という記事を書いています。<br />その中で <a href="http://www.siesta.co.jp/aozora/archives/001841.html" target="_blank">aozora blog: オリジナリティについて</a> から引用した部分に注目しました。</p>
<blockquote>
<p>ぼくのオリジナリティ。それはつきつめると、ぼくがいつどこでなにをやって、なにをやらなくて、何を考えて何を考えなくて、という「履歴」だということに 思い至ったわけでした。べつにどうということはない、ちんぷであたりまえのことなんですが。どこにどれくらい住んだことがあったか。そこでどんなことをし たか。どんな人と出会ったか。なにを食べたか。なにを聞いたか。なにをたのしんだか。なににおどろいたか。なにを悩んだか。なにを遊んだか。読書の履歴。 失恋の履歴。仕事の履歴。学習の履歴。病気やけがの履歴。思考の履歴。情報の履歴。それから家族の履歴。</p>
</blockquote>
<p>つまりは、今まで何をやってきてどう感じたかを人生のログファイルとして残そうということでしょうか。どんな映画を見たのか、どんな人と出会い、または別れたのか。人生で経験してきたことにオリジナリティが存在するという考え方だと捉えました。</p>
<p>当然ながら、経験する事というのは良いことばかりではありません。失敗したことなど、苦い部分も人生のログファイルとして記録することになるわけです。むしろ、ログファイルはそういった失敗(エラー部分)をきちんと残すものだと思います。</p>
<p><a href="http://www.yamaha.co.jp/design/index_f.html">YAMAHA</a> Outside Yamaha 佐藤卓さん<br />(Flashなので、場所をインデックスページしか紹介できません)</p>
<blockquote>
<p>自分の中にたくさんの引き出しを持てという言葉をよく聞きますが、僕は引き出しなんて持つ必要すらないと思っています。第一、重すぎて持って歩くのが大変でしょう。引き出しという荷物、つまり過去の経験に囚われていたら失敗してしまいますよ。時代が変わって新しいことが可能になったのに、「できるはずがない」と思いこんだままになってしまう危険もあるのではないでしょうか。</p>
</blockquote>
<p>でも、ログファイルは過去の経験を引きずるために残すわけではありません。"できるはずがない"という思い込みを打破する、あるいは和らげるためです。何故、失敗したのかを考えるためにあるのであって、落ち込んだり、後悔の念で自己を囲い込むためには存在しません。</p>
<h4>相手に全力で伝えようとする挑戦</h4>
<p><a href="http://d.hatena.ne.jp/gothedistance/20090223/1235362716" target="_blank">GoTheDistance: オリジナリティのつくりかた</a></p>
<blockquote>
<p>不思議なもので、「自分が考えたこと&times;自分がやってきたこと」だけは誰とも重なることが無いんですね。<br /> ですが、この公式が「&times;」を採用しているのは、考えたことがゼロなら独創性なんて生まれないよっていう示唆でもあります。</p>
</blockquote>
<p>"誰とも重なることが無い"部分。おそらく、それは相手に全力で伝えようとする挑戦をしない限り、誰もわかってくれません。その挑戦はとてつもなく時間と勇気を必要とするもので、めんどくさいとか、だるいと感じて、モチベーションが･･････なんて言葉を使いたくなってきます。</p>
<p>けれども、それに伝えようとする姿勢を他人に見せないと独創性を発揮する場なんて確保できません。個性的な発想を掴むことから離れてしまい、期待したい結果とは真逆の方向を進みます。</p>
<h4>"俺には俺のスタイルがある"は衰退を導く</h4>
<p>この前、<a href="http://www.apple.com/jp/retail/dreamclassroom/" target="_blank">Dream Classroom</a> で坂本龍一さんのお話を聞けたのですが、そのときの内容がすでにWEBに載っています。</p>
<p><a href="http://ascii.jp/elem/000/000/218/218272/index-4.html" target="_blank">ASKII.jp: ミスチルを目指して終わるな──坂本龍一かく語りき</a></p>
<blockquote>
<p>そうそうそう。俺たちはこういうものは必要ない、こういうものが必要だと、自分たちで考えて提案すればいいんだ、と思うけどな。</p>
</blockquote>
<p>ここで大事だと僕が感じた部分は、"俺たち"や"自分たち"というところです。一人ではなく、複数人で提案するという点がとても重要だと感じます。</p>
<p><a href="http://anond.hatelabo.jp/20090309000607" target="_blank">はてな匿名ダイアリー: ５年間、練習してもだめな人がまともになるためにするべきこと</a></p>
<blockquote>
<p>俺には俺のスタイルがある<br /> というのは新しい技術体系を作るということに他なりません<br /> そういうのは天才に任せておいてください</p>
</blockquote>
<p>"俺には俺のスタイルがある"と主張することは、研究ということになり、多くの時間をそのことに費やすことになると想像します。ただ、もしかしたら、一度どこかでUターンしないと後にも先にも行けなくなってしまうかもしれません。僕にはそんなことをする度胸はありません。途中で力尽きそうだ。</p>
<h4>"多くの段階を踏む"というのは</h4>
<p>ログファイルを残すということです。<br />では、それはどうやって作るのか。</p>
<ul>
<li><span>一人ではなく、複数人(コミュニティ)で行うこと</span></li>
<li><span>各々の挑戦を尊敬し、それを参考にすること</span></li>
<li>"俺のスタイル"ではなく、まずは型にはまる術を身につけること</li>
</ul>
<p>そうすれば、自然と履歴が残っていくのではないでしょうか。<br />また、個性的な発想を掴むために何をするべきかということも自然とわかってくる気がします。</p>
