#+TITLE: IE6では車検は通れない
#+DATE: 2009-08-13T23:46:29+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

Internet Explorer 8をインストールしました。<!--more-->

IE8は今までのバージョンと違いWEB標準への対応がきちんと取られています。IE6が公開されたのはインターネットを見る限り2001年8月末だそうですが、長期に渡って使われてきたこのIE6に取って代われるブラウザになっています。

2001年8月末の頃の私はまだインターネットというものが具体的にどういったものを指すのかなど全く知らず、ましてやパソコンの電源の入れ方すらも知りませんでした。当然ながらパソコンが全く分からないという頃は先輩に教わったり、友人に教わったりしていました。そういったこともあって初めて使ったブラウザはInternet ExplorerではなくFirefoxでした。そして下記のようなことからInternet Explorerとは早々に距離をおくようになりました。
<ul>
	<li>"インターネットへのアクセス ＝ Internet Explorerを使う" といった考えが定着することがなかった</li>
	<li>ブラウザが複数存在することをパソコンを使い始めたころから知ったため、WEB標準という言葉に抵抗がなかった</li>
	<li>WEB標準という言葉に関連してAcidというものを知り、Internet Explorerがそれに準拠していないことを知った</li>
</ul>
随分と前になりますが、HTMLやCSSを勉強する際に本を探していた時がありました。インターネットでいくらでも資料は見つかりましたが、ディスプレイを長時間みることに慣れていなかったということと、インターネットにあるHTMLやCSSの情報はある程度理解した人が見るものだと思ったからでした。当時は体系としてきちんとまとまっている本を欲しがっていました。そのため、HTMLタグを延々と詳しく解説しているようなものではなく、“手をここまで動かすとこういったものが作れる”といった本を買いました。

本の購入と同じ時期にFirefoxのアドオン(プラグイン)であるFirebugというの存在を知りました。これはHTML, CSS, jsを表示させるだけでなく、ブラウザ上で確認しながら書いていくことができます。リロードしてしまえば、キャッシュされたものを使っていたりするためか消えてしまいますが、すぐさま変更が画面に反映されるFirebugに当時はとても感銘を受けました。Ineternet Explorer 6にも"<a href="http://www.microsoft.com/downloadS/details.aspx?familyid=E59C3964-672D-4511-BB3E-2D5E1DB91038&amp;displaylang=en" target="_self">Internet Explorer Development Toolbar</a>"というのインストールすれば似たようなことできましたが、使い勝手が良いとは言い難いものでした。

Internet Explorer 8では使い勝手が大変良い開発ツールが標準装備されています。また、Internet Explorerのバージョン違いでウェブページの表示が異なるといった問題は多くの人を悩ませていましたが、これもMicrosoftから出ているSuperViewといったツールを使うことで確認が容易となり、適切なウェブページ表示のための修正もしやすくなります。Windowsが入っているパソコンを複数台用意するといったような手の込んだ方法などを用いる必要がなくなります。

Internet Explorer 6は公開されてから8年も経ちます。公開当時は先進的だったかもしれませんが、ウェブ2.0の今のインターネットでは手を引っ張ることはできず、追いついてもいけず、それどころか足を引っ張っていると言わざるをえません。

本日から"<a href="http://www.ie6nomore.com/">IE6 No More</a>"に参加しました。
