#+TITLE: High-Defコンテンツの制作期間は顔合わせで決めます
#+DATE: 2009-09-26T10:03:34+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

各ゲームの制作者との顔合わせに向けて準備を行います。<!--more-->私の場合、ここで品質の差がでると思っています。制作期間もここで決まると考えています。そのため、きちんとヒアリングは行いたいと思っています。できる限りの準備を行い顔合わせに備えます。

ひとまずは"簡単な映像"を作成しました。スタッフ間で共通認識を多く持つためです。ただし、これはVコンテ、 アニマティクスといったものではありません。尺が30秒で良いのか、60秒の方が良いのか、90秒のものが良いのかの判断をするための材料です。素材は何が必要なのかを叩き出すために作ったものでもあります。この映像は最終的に作り上げる映像の構成を練り上げるためには使いませんし、使ってはいけないものだと考えています。後々、この映像は廃棄します。

作成した"簡単な映像"の結果を踏まえ"字コンテ"というものに書きます。文字のみで映像の構成を書いていくものです。ただし、これは構成表のようなものではありません。後日、正式なものとして絵コンテを別途用意します。

コンテを作るためには各ゲームの世界観などストーリーないしシナリオ部分の分析から入ります。こうすることで伝えてなくてはいけない部分を把握することが出来ます。この時、正確さは求めずにひとまず抽出してコンテに描いていきます。

そういった準備が済んだら、顔合わせを行います。顔合わせでは作品において肝となるキーワードやグラフィックデザインのコンセプトなどをゲームの制作者に伺います。この際、可能であればきちんとしたヒアリングシートを用意するのが最善でしょう。間に合わなければメモ書き程度のものでも事足りはします。

後日、それを順次反映させていきます。そのため、After Effectsを始めとしたソフトウェア上では画像差し替えなどがしやすいように考えながら作成していきます。ここでどのぐらい工夫できたかで終盤に差が出てきます。今回、制作を担当するチームが3つであるためと締切まで日がないということから、この作業を行い柔軟性を高めることはとても重要でした。

8月下旬で、1チームあたりに割ける制作時間が12±2といった状況になっていました。
