#+TITLE: 事業所閉鎖、会社閉鎖
#+DATE: 2009-03-07T13:21:56+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4>事業所閉鎖、会社閉鎖</h4>
<p>以前、<a href="http://www.hiroakit.com/blog/2009/02/post_07.html" target="_blank">The Orphanage</a> という記事を書きました。これは経営(経済)的な意味での閉鎖でした。今回、これとは違う視点から考えている記事をWEBで発見しました。<a href="http://www.hiroakit.com/blog/2009/02/post_07.html" target="_blank"><br /></a></p>
<p><a href="http://d.hatena.ne.jp/Chikirin/20090208" target="_blank">Chikirinの日記：インフルエンザにしろ風邪にしろ</a></p>
<blockquote>
<p>しかしながら今のところ会社が風邪やインフルエンザで「事業所閉鎖」とか「会社閉鎖」になった、という話を聞いたことがない。過去にそういう例があるのだろうか？</p>
</blockquote>
<p>学級閉鎖、学校閉鎖があるのは想像がつきますが、事業所閉鎖、会社閉鎖といった現象を耳にしたことはないです。新聞やテレビなどでそういった情報を出会ったことがないだけかもしれないけど、まぁ、まずなさそうですよね。</p>
<p>とにもかくにも、こういう発想を持ったことは無かった。</p>
<h4>Chikirinの日記：インフルエンザにしろ風邪にしろ にコメントされた内容<br /></h4>
<p><a class="hatena-id-icon" href="http://d.hatena.ne.jp/Sauna_wear/">Sauna_wear</a> さん</p>
<blockquote>
<p>昔勤めていた中堅の出版社で、12月から２月くらいまで常にマスク着用の人がいました。他部署なので顔見知り程度ですが（お互いに）いちど、休憩室で「風邪ですか？」と聞いたら「予防です」と言われました。たしかに、風邪くらいでは会社を休めない人が多めの業種なんでそういうのも必要かなと。（健康体だとしても長時間労働できっついので、風邪なんか引いてたらそれこそ致命的なミス＆精神的に辛い）その人は風邪の時期に必ずマスクマンです。</p>
</blockquote>
<p><a class="hatena-id-icon" href="http://d.hatena.ne.jp/Gilliam/">Gilliam</a> さん</p>
<blockquote>
<p>ゴホゴホしながら会社に出てくるのがカッコいいとか思ってるのが多くて困る・・・なんか中年になってくると、体の調子の悪さ自慢？みたいなのがはやりだすのも、どうなの？って感じ。と、流行の最初と最後に風邪を貰う僕が言うと、お前の体調管理どうなの？って言われそうだけど(^^;;</p>
</blockquote>
<p>最近、マスクはずっと着けてます。うがいとかも極力するようにしてます。こういうのに気を使うのって慣れるまで面倒に感じます。けれども、風邪を引いてしまって予定が狂ったりしてしまったときの方が面倒です。</p>
<p>話が脱線しますが、amadana製のマスクとかがあったら、結構売れるんじゃないでしょうか？<br />amadanaは家電メインのところだから、絶対にやらないと思いますが、デザイナーマスクみたいのがあったら面白いですよね。この曲線、このベジェ曲線が美しい！！みたいな。</p>
<p>&hellip;&hellip;、一部の人しか使わないか。そもそも消耗品なのに、それが高かったら誰も買わないですね。</p>
<h4>結論<br /></h4>
<p><span>風邪引いても、仕事は休めない</span>という考えは納得です。事実、そういう現象になっているのであれば仕方がありません。でも、体調管理も大事な仕事の一つです。</p>
<p>僕の考えだと、風邪を引いてしまうのは<span>体調管理という仕事を休んだ</span>ことになります。 (けれども、そう思っている自分も結構風邪を引くのでなかなか難しいところですが)</p>
<p>とりあえず、マスクが世の中にあることに感謝。</p>
<ul>
<li> <a href="http://www.amazon.co.jp/gp/product/B000LROD5A?ie=UTF8&amp;tag=largeworld-22&amp;linkCode=as2&amp;camp=247&amp;creative=1211&amp;creativeASIN=B000LROD5A">超立体 マスク花粉用 ふつう 30枚</a> </li>
<li><a href="http://www.amazon.co.jp/gp/product/B000X8JG1I?ie=UTF8&amp;tag=largeworld-22&amp;linkCode=as2&amp;camp=247&amp;creative=1211&amp;creativeASIN=B000X8JG1I">アイリスオーヤマ プリーツマスク Mサイズ NMK-60PM 60枚入</a></li>
</ul>
