#+TITLE: "Pixieでネットワークレンダリング"
#+DATE: 2009-04-09T09:50:00+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4>RIBファイルをネットワークでレンダリングする</h4>
<p>そんな大したことしてないんですけどね(笑<br />試しにひとまずとりあえず、やってみたかった。<br />今回はひとつのRIBファイルをレンダリングしただけです。</p>
<h5>環境</h5>
<p>サーバーのIPはありえないけど、そういうIPだということで。</p>
<ul>
<li>クライアント： WindowsXP </li>
<li>サーバー： WindowsXP (000.000.0.0)</li>
<li>RenderMan: Pixie</li>
</ul>
<h5>Windowsのファイアフォール<br /></h5>
<p>一度試しにクライアントからサーバーに ping が 打ってみてください。全く反応がありません。その原因はファイアフォールが有効にしているためみたいです。なので、一時それを切ります。コントロールパネルからWindowsファイアフォールのところで設定し直してください(勿論、することが終わったらすぐに有効にします)。 確認のため、ping が打つと無事通るはずです。</p>
<p>それと、たまたまコマンドコロンプトで net view と打ったんだけど システム エラー 6118 と返ってきた。ま、いっか。ネットワークはよくわからない。</p>
<h5>ポート 24666 の許可</h5>
<p>今回、ネットワークレンダリングする際にポート24666を使います。<br />そのため環境によっては(一時的にでもいいので)有効にする必要があるかもしれません。</p>
<h4>レンダリングマシンとして起動させる</h4>
<p>サーバーでPixieを起動させて、コマンドを打ちます。</p>
<pre>rndr -r</pre>
<p>こういう返事が来たら、起動成功です。</p>
<pre>Active at 000.000.0.0:24666</pre>
<h4>レンダリングマシンを指定する</h4>
<p>クライアントでコマンドを打ちます。</p>
<pre>rndr -s 000.000.0.0:24666 RIBファイル名<br /></pre>
<p>すると、IP 000.000.0.0 のマシンでRIBファイルがレンダリングされます。<br />イメージ画像はクライアントマシン上に保存されます。</p>
