#+TITLE: Pixar と アカデミー賞
#+DATE: 2009-03-08T00:30:00+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4>Pixar と アカデミー賞<br /></h4>
<p>第81回アカデミー賞で WALL-E が長編アニメを受賞したことは、まだ記憶に新しいと思います。WALL-E を制作したのは、いうまでもなくあの Pixar です。この WALL-E の前にも何度かアカデミー賞を受賞していたような気がしたので、調べてみました。</p>
<ul>
<li>第76回アカデミー賞長編アニメ受賞: ファインディング・ニモ Finding Nemo （2003年）</li>
<li>第77回アカデミー賞長編アニメ受賞: Mr.インクレディブル The Incredibles （2004年）</li>
<li>第80回アカデミー賞長編アニメ受賞: レミーのおいしいレストラン Ratatouille （2007年）</li>
<li>第81回アカデミー賞長編アニメ受賞: WALL・E/ウォーリー （2008年）</li>
</ul>
<p><a href="http://d.hatena.ne.jp/tadamasa/20090223/1235405860">ただまさの日記:ピクサーの長編アニメ「ウォーリー」がアカデミー賞受賞！</a>を参考にさせていただきました。この方(tadamasa さん)の記事にはアカデミー賞の短編アニメ部門で受賞した作品についても記載されています。</p>
<h4>きれいなCG<br /></h4>
<blockquote>
<p>ずーっと見てみると、2003年の<a class="keyword" href="http://d.hatena.ne.jp/keyword/%a5%d5%a5%a1%a5%a4%a5%f3%a5%c7%a5%a3%a5%f3%a5%b0%a1%a6%a5%cb%a5%e2">ファインディング・ニモ</a>あたりまでは、CG技術の進歩も合わせて楽しんでたけど、最近はCG技術はもう行くとこまで行っているように思う。<br /> このウォーリーでも、CGでしか表現できない場面も多かったけど、もうCGがすごい、という感想ではなく、単純に映画としてすごい！きれい！楽しい！っていう感じ。</p>
</blockquote>
<p>tadamasa さんがこう仰ってるけど、それはとても納得します。確かに最近のフルCGアニメってきれいで、特に WALL-E って舞台に宇宙があったから、余計にそれが神秘的に見えたりもしました。</p>
<h4>ビジネスとして</h4>
<p>きれいなCGを作れるから、ビジネスとしてうまくいっているかは疑問ですよね。Pixar の場合は<a href="http://www.pixar.com/jp/renderman/whats.html" target="_blank">RenderMan</a>というソフトウェアを販売してるってことがあるから、ビジネスとしてはうまくやっていってるのかなぁ・・・・・・と考えますが、実際のところどうなんでしょうか。</p>
<p>CGソフトウェアの販売代理をしているボーンデジタルさんで価格を調べてみました。(調べたところで、あまり意味無いんでしょうけれどもね）</p>
<p><a href="http://www.borndigital.co.jp/software/price/renderman.html" target="_blank">ボーンデジタル:RenderMan 販売価格</a></p>
<ul>
<li><strong>RenderMan Studio</strong><strong> </strong>￥294,000 </li>
<p>RenderMan for Mayaの機能にプラスして、オリジナルのシェーダーを作成可能な管理ツール「Slim」、スクリプトベースのコンポジティング機能を持つ高速なイメージ ツール「it」、効率よくレンダリングジョブをマネージメントするジョブ管理ツール「Alfred」などが付属します。また、RIBファイル出力も可能と なっておりますので、大規模なプロジェクトにも対応可能です。シーンを構築するデザイナーに必要なライセンスになります。</p>
<p>&nbsp;</p>
<li><strong>RenderMan Pro Server</strong><strong> </strong>￥525,000</li>
<p>RenderMan Pro Serverがあれば、どんなサーバやワークステーションでもレンダリングマシンにできます。RenderMan Studioで作成したRIBファイルをレンダリングする際に必要なライセンスです。</p>
</ul>
<p>学生が買うソフトではなさそうです(笑<br />仮にこんなにお金を持っていたとしても、おそらく Mac Pro だったりハードウェアの購入を考えます。ただ、B to B としてなら、まぁ普通なのかなと思いますが、詳しいところはわからず終い。</p>
<p>ところで、最後に疑問。<br />Pixarって上場してるのでしょうか。</p>
