#+TITLE: Liquid(コンパイル編): Part 3
#+DATE: 2009-04-03T02:45:00+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4>コンパイル: XX回目</h4>
<p>実際にやっていたときにやったコンパイルの回数、とても多かったと思います。<br />なんだかんだいって、ちょっとずつ前に進んでいけたのでとても良かったです。</p>
<h4>もしかしたら・・・・・・</h4>
<p>ひとつだけ、ちょっとうろ覚えなんですけども・・・。</p>
<p>Visual Studio に 「liqRibTranslator.cpp を unicode で保存し直してください」みたいなことを言われたような、言われなかったような、記憶が曖昧な部分があります。もしかしたら、これまでの記事通りにやったら、それが原因でうまくいかないかもしれません。たぶん、その場合もソースコードをSVNでダウンロードしたら解決するかもしれません。（プログラミング、わからないことだらけで、あくまでも楽観的な予想になってしまいます。</p>
<h4><a name="pixie_error"></a>Pixie だけうまくいかない</h4>
<p>コンパイルの際、Pixie Release にすると、Liquid本体だけがうまくコンパイルできません。<br />displaydriveのコンパイルは成功しています。</p>
<pre>1&gt;   ライブラリ .\../../bin/Pixie/win32/Release/Objects/liquid.lib とオブジェクト .\../../bin/Pixie/win32/Release/Objects/liquid.exp を作成中<br />1&gt;liqPreviewShader.obj : error LNK2019: 未解決の外部シンボル _RI_VERBATIM が関数 "int __cdecl liquidOutputPreviewShader(class std::basic_string&lt;char,struct std::char_traits&lt;char&gt;,class std::allocator&lt;char&gt; &gt; const &amp;,struct liqPreviewShaderOptions const &amp;)" (?liquidOutputPreviewShader@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABUliqPreviewShaderOptions@@@Z) で参照されました。<br />1&gt;liqRibClipPlaneData.obj : error LNK2001: 外部シンボル "_RI_VERBATIM" は未解決です。<br />1&gt;liqRibTranslator.obj : error LNK2001: 外部シンボル "_RI_VERBATIM" は未解決です。<br />1&gt;liqRiCommands.obj : error LNK2001: 外部シンボル "_RI_VERBATIM" は未解決です。<br />1&gt;liqPreviewShader.obj : error LNK2019: 未解決の外部シンボル _RI_BILINEAR が関数 "int __cdecl liquidOutputPreviewShader(class std::basic_string&lt;char,struct std::char_traits&lt;char&gt;,class std::allocator&lt;char&gt; &gt; const &amp;,struct liqPreviewShaderOptions const &amp;)" (?liquidOutputPreviewShader@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABUliqPreviewShaderOptions@@@Z) で参照されました。<br />1&gt;liqPreviewShader.obj : error LNK2019: 未解決の外部シンボル _RI_P が関数 "int __cdecl liquidOutputPreviewShader(class std::basic_string&lt;char,struct std::char_traits&lt;char&gt;,class std::allocator&lt;char&gt; &gt; const &amp;,struct liqPreviewShaderOptions const &amp;)" (?liquidOutputPreviewShader@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABUliqPreviewShaderOptions@@@Z) で参照されました。<br />1&gt;liqPreviewShader.obj : error LNK2019: 未解決の外部シンボル _RI_RGBA が関数 "int __cdecl liquidOutputPreviewShader(class std::basic_string&lt;char,struct std::char_traits&lt;char&gt;,class std::allocator&lt;char&gt; &gt; const &amp;,struct liqPreviewShaderOptions const &amp;)" (?liquidOutputPreviewShader@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABUliqPreviewShaderOptions@@@Z) で参照されました。<br />1&gt;liqRibTranslator.obj : error LNK2001: 外部シンボル "_RI_RGBA" は未解決です。<br />1&gt;liqPreviewShader.obj : error LNK2019: 未解決の外部シンボル _RI_RGB が関数 "int __cdecl liquidOutputPreviewShader(class std::basic_string&lt;char,struct std::char_traits&lt;char&gt;,class std::allocator&lt;char&gt; &gt; const &amp;,struct liqPreviewShaderOptions const &amp;)" (?liquidOutputPreviewShader@@YAHABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABUliqPreviewShaderOptions@@@Z) で参照されました。<br />1&gt;liqRibTranslator.obj : error LNK2019: 未解決の外部シンボル _RI_COMMENT が関数 "private: class MStatus __thiscall liqRibTranslator::ribPrologue(void)" (?ribPrologue@liqRibTranslator@@AAE?AVMStatus@@XZ) で参照されました。<br />1&gt;liqRiCommands.obj : error LNK2001: 外部シンボル "_RI_COMMENT" は未解決です。<br />1&gt;liqWriteArchive.obj : error LNK2001: 外部シンボル "_RI_COMMENT" は未解決です。<br />1&gt;liqRibTranslator.obj : error LNK2019: 未解決の外部シンボル _RI_FOV が関数 "private: class MStatus __thiscall liqRibTranslator::framePrologue(long)" (?framePrologue@liqRibTranslator@@AAE?AVMStatus@@J@Z) で参照されました。<br />1&gt;liqRibTranslator.obj : error LNK2019: 未解決の外部シンボル _RiBSplineBasis が関数 "private: class MStatus __thiscall liqRibTranslator::objectBlock(void)" (?objectBlock@liqRibTranslator@@AAE?AVMStatus@@XZ) で参照されました。<br />1&gt;liqWriteArchive.obj : error LNK2001: 外部シンボル "_RiBSplineBasis" は未解決です。<br />1&gt;../../bin/Pixie/win32/Release/liquid.mll : fatal error LNK1120: 外部参照 8 が未解決です。<br />1&gt;ビルドログは "file://d:\lab\renderman\liquid\workspace\bin\Pixie\win32\Release\Objects\BuildLog.htm" に保存されました。<br />1&gt;liquid - エラー 16、警告 54<br /></pre>
<p>外部シンボルってなんなんだろう。。。<br />うーん・・・、ヘッダーファイルとか、関連づけ？<br />リンクのことかな？</p>
<p>理由はわからないですが、ひとまずはここまで。</p>
<p>今回は、Releaseでコンパイルしたけれども、<br />その状態ならPixieを使ったRIB書き出し(?)もOK!ってことになるんでしょうか。</p>
<p>うーん・・・、それもわからない。</p>
