#+TITLE: "なぜ、たくさん働くのか？"
#+DATE: 2009-03-07T12:50:40+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4>なぜ、たくさん働くのか？</h4>
<p><a href="http://d.hatena.ne.jp/eliya/20090227/1235746870" target="_blank">eliyaの日記:なぜ日本人はたくさん働くのか？</a></p>
<blockquote>
<p>簡単に結論から書くと、日本はクビになったときのペナルティが高いから、会社に服従するしかなくて、労働時間が延びる、ということです。</p>
</blockquote>
<p>日本のケースだと、このような理由が一般的なのでしょうか。就職活動している人間としてすごく気になるエントリーです。たとえば、"会社に服従する" という部分はどういう意味なのか、うまく想像できません。((好きで会社というコミュニティに入った&hellip;&hellip;わけではないのか？</p>
<h4>日本の労働市場は二重構造</h4>
<p>この記事には、"日本の労働市場は二重構造"だとあります。</p>
<blockquote>
<p>第一次労働市場: 高賃金であり、教育訓練の機会が多く、雇用や賃金もきちんとした規則や慣行で定められる。<br /> 第二次労働市場：低賃金であり、教育訓練の機会が少なく、雇用が不安定で、教育や訓練を受けても報酬はわずかしか増えない。</p>
</blockquote>
<p>さらに、このように続きます。</p>
<blockquote>
<p>僕の理解では、スキルが必要な複雑な仕事を行うのが第一次労働市場で、比較的単純な作業を行うのが第二次労働市場です。この違いのポイントは、第二次労働市 場では「教育や訓練を受けても報酬はわずかしか増えない。」という点です。スキルを持った人が第一次市場から第二次市場に移ると、給与は低下します。これは第二労働市場が第一労働市場にくらべて差別されているからじゃなくて、第二労働市場では積み重ねてきた教育やスキルを有効に活用できないことに由来します。</p>
</blockquote>
<p>確かに、3dsMaxを使えるからってコンビニでバイトしても、その能力が生かすことは、まず無理ですものね。それだったら、その能力を生かせる場所を探すといった選択肢の方が賢明そうですね。(CG、全然わかりませんけれども)</p>
<p><a href="http://d.hatena.ne.jp/eliya/20090227/1235746870" target="_blank">eliyaの日記:なぜ日本人はたくさん働くのか？</a> に"石川および出島による80年および90年のデータを使った実証分析" と書いてあるので、以前から、スキルの有無で報酬に差が出るのは必然だと考えても良さそうです。</p>
<h4>知識労働者</h4>
<p>"スキルが必要な複雑な仕事を行うのが第一次労働市場" の部分は、つまり<span>知識労働者</span>のことかなと思いました。最近、 <a href="http://www.amazon.co.jp/gp/product/4478190453?ie=UTF8&amp;tag=largeworld-22&amp;linkCode=as2&amp;camp=247&amp;creative=1211&amp;creativeASIN=4478190453">ネクスト・ソサエティ ― 歴史が見たことのない未来がはじまる</a> をかじって読んだのですが、その本の(確か)21頁にこう書いてありました。</p>
<blockquote>
<p>知識労働者とは新種の資本家である。なぜならば、知識こそが知識経済における主たる生産手段、すなわち資本だからである。今日では、主たる生産手段の所有者は知識労働者である。</p>
</blockquote>
<p>他にも、"知識は急速に陳腐化する。"ともその本には書いてありました。(結局のところ、恥ずかしいことに読んでも全く理解できなかったです。汗水流して働くほかに、知識を武器にして働く方法もありますよ、ってことなのかなとは感じ取れましたけども。)</p>
<h4>番外編<br /></h4>
<p>この記事に対するコメントで興味を持ったもの。このコメントで "リファレンス" という言葉を初めて知りました。</p>
<blockquote>
<p>転職活動が盛んな海外では「リファレンス」という行為が行われます。電話なんかで前職同僚や上司に転職希望者の評判を聞いて、自社に合う人物かどうか意見を聞いたりする行為です。</p>
</blockquote>
