#+TITLE: "2009年の技術目標"
#+DATE: 2009-02-11T10:48:41+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4>今年に意識すること</h4>
<p>「<a href="http://blog.taikomatsu.com/2009/02/05/%E4%BB%8A%E5%B9%B4%E3%81%A8%E6%9D%A5%E5%B9%B4%E3%81%90%E3%82%89%E3%81%84%E3%81%AB%E6%84%8F%E8%AD%98%E3%81%97%E3%81%A6%E3%81%93%E3%81%AA%E3%81%99%E3%82%BF%E3%82%B9%E3%82%AF/" target="_blank">今年と来年ぐらいに意識してこなすタスク</a>」より</p>
<blockquote>
<ul>
<li>Mayaなどの3Dアニメーションパッケージに精通していること</li>
<li>MEL/Python/Perlなどスクリプト言語の知識</li>
<li>MayaAPI/mental ray shader APIなど、C/C++の知識</li>
<li>mental ray/RenderManの経験、知識</li>
<li>(LightingTDとかだと）シェーダ言語の経験、知識</li>
<li>UNIX系OSが扱えること（ここにsh/cshの知識が含まれてる場合もある）</li>
<li>大学卒業レベルの数学（特にシェーダライター辺りの募集に多いかも）</li>
<li>コンピュータサイエンスまたはアート関連の大学を卒業</li>
</ul>
</blockquote>
<p>memlog というブログから引用しました。海外のプロダクションを例にとって、CGをやっていく上で必要となるであろう技術がまとめられています。主にTD向けですが、今回はこれを参考にしてみます。</p>
<p>&nbsp;</p>
<h4>自分なりの視点から</h4>
<ul>
<li>Mayaなどの3Dアニメーションパッケージに精通していること</li>
<p>僕の場合だと3dsMaxだけれども、いまはソフトの違いは気にしない。<br /> アニメーションについて理解を深めていこうと思います。</p>
<br />
<li>MEL/Python/Perlなどスクリプト言語の知識</li>
<p>Python、最近全くいじってないですね。今年こそはなんとかものにしたい。</p>
<br />
<li>MayaAPI/mental ray shader APIなど、C/C++の知識</li>
<p>Pythonも大事ですが、C/C++も大事。<br /> まずはどっちから習得するか決めないとね。</p>
<br />
<li>mental ray/RenderManの経験、知識</li>
<p>RenderManか。大学にあったようななかったような・・・。<br /> それよりも、まずはmental rayを扱えるようにならないとダメか。</p>
<br />
<li>(LightingTDとかだと）シェーダ言語の経験、知識</li>
<p>シェーダ言語までは取りかかれそうもないですね。<br /> 全く興味がない分野じゃないのだけれども、他の事も考えると難しい。<br /> もしやるとしたら、夏頃とか沢山時間が取れるときに一気にやりたい。</p>
<br />
<li>UNIX系OSが扱えること（ここにsh/cshの知識が含まれてる場合もある）</li>
<p>新年度には卒研が始まります。その時にLinux（FedoraかUbuntu）を使おうと考えています。研究で使えなくても、もっとLinuxを使う習慣を付けたい。</p>
<br />
<li>大学卒業レベルの数学（特にシェーダライター辺りの募集に多いかも）</li>
<p>実は1月の半ばぐらいから数学をやり始めた。いまでも続いているから習慣化はされたかな。ゆっくりと気長にやっていきます。ただ、アルゴリズムの話とはまだ無縁の状態なので、あまりゆっくりともしていられない。</p>
<br />
<li>コンピュータサイエンスまたはアート関連の大学を卒業</li>
<p>僕が通っている大学ってどうなんだろう。よくわからない区分です。<br /> 工科大学だから、一応コンピュータサイエンスに分類できるのでしょうか。<br /> とりあえず、芸術大学ではないことは確かですね。</p>
</ul>
<h4>学ぶべき事は多い</h4>
<p>学ぶべき事は多い。けれども、時間のことを考えると学べることは多くない。なんていったって、今年は就職活動をやらないといけません。卒研で結果を残さないといけません。それらをおろそかにするとCGがどうとか言っていられなくなりますから、これは必死です。</p>
<p>とりあえず、Ubuntuをもっと使うようにする。PythonかC++を使うようにする。mental ray をひたすら使う。<span>勉強の経過をブログに載せまくる。</span>それから絵も書いて書いて書きまくる。</p>
<p>がむしゃらにやる方法じゃだめだな。もう少しだけ賢くやっていく方法を探します。<br /><span>GeneralistじゃなくてSpecialistを目指せるようにもっと絞ろう。</span></p>
