#+TITLE: C言語入門してみた　Part2
#+DATE: 2009-04-24T08:15:00+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4>Chapter8: 条件文</h4>
<p>条件文というのはある動作をするかしないかの基準が含まれている文です。これを表現するには if を使います。(他にも switch がありますが、今は割愛します。)</p>
<p>例えば、人間だと「夜にシュークリーム食べると太るから食べない」といったような動作を自然とこなしますが、これを条件として立てる場合「夜なら、シュークリーム食べるな」という表現になります。</p>
<h5>if</h5>
<p>基本的にはこんな感じで組み立てていくみたい。</p>
<pre>if(条件) {<br /><br />条件がとれたときに実行する文<br /><br />}<br /><br />else {<br /><br />条件が取れないときに実行する文<br /><br />}</pre>
<h5>else if</h5>
<p>条件をさらに増やす方法として else if は用いるみたい</p>
<pre>if(条件A) {<br /><br />条件Aのみに当てはまったときに実行する文<br /><br />}<br /><br />else if (条件B) {<br />条件Bのみに当てはまったときに実行する文<br />}<br /><br />else {<br /><br />条件A、条件Bに当てはまらないときに実行する文<br /><br />}</pre>
<h5>真と偽</h5>
<p>制御式の判定結果を表現するとき真と偽と言う言葉を用いるそうです。具体的には真が条件を正しくとれていた場合で、偽が条件を正しく取れていなかった場合です。この両者を合わせて真偽値と呼ぶこともあるそうです。</p>
<p>例えば、変数cが200だったとして</p>
<p>if(c&gt;100) というものだったら、これは真です。</p>
<p>if(c&gt;300) というものだったら、これは偽です。</p>
<h5>関係演算子、等価演算子、倫理演算子</h5>
<p>関係演算子というのは、&gt;, &gt;=, &lt;, &lt;= といったもののこと。<br />等価演算子というのは、==, != といったもののこと。!= は等しくないことを表す。<br />倫理演算子というのは、&amp;&amp;, ||, ! といったもののこと。&amp;&amp; は倫理積のことで"AかつB"を表現したい時に使う。|| は倫理和で "AまたはB" のときに使う。! は否定する時に使う。</p>
<p>閏年の表現</p>
<p>閏年は、「4で割りきれて、かつ100で割り切れない年である。あるいは400で割り切れる年のこと」みたいです。</p>
<pre>if(n%4 == 0 &amp;&amp; n%100 != 0 || n%400 == 0) {<br />&nbsp;printf("閏年です\n");<br />}<br />else {<br />&nbsp;printf("閏年ではありません\n");<br />}</pre>
