#+TITLE: mental ray 4日目
#+DATE: 2009-02-25T07:10:00+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

<h4>照明(ライティング)</h4>
<p>なぜ、光を当てるのか。</p>
<p>ぼくは、<span>「対象物を完全な3次元形状として表すために使う」</span>と大学の先輩に教わったけども、残念なことに完全に理解できていない。かといって、全くわからないわけでもなく。かといって、わかるって言えるものでもなく。発展途上の状態。</p>
<p>今回は、照明(ライティング)について考えます(かなり浅く)。</p>
<h4>ライトの種類</h4>
<p>照明の種類は大体こんな感じです(エリアライトとアンビエントライトの説明には自信がないです)。ちなみに、ソフトウェアによってライトの名前や使えるライトの種類が異なる場合があるそうです。</p>
<ul>
<li>オムニライト(Mayaだと、ポイントライト)</li>
<p>一つの光源から全方向に光を放ちます。</p>
<li>スポットライト<br />
<p>収束された光源を放ちます。</p>
</li>
<li>指向性ライト(Mayaだと、ディレクショナルライト)
<p>単一方向に平行な光を放ちます。</p>
</li>
<li>エリアライト</li>
<p>オムニライトと似ているけども、たしかちょっと違う。ライト自体の大きさと光量が関係性を持っていたような気がします。<span>よくわかりません。</span></p>
<li>アンビエントライト</li>
<p>Mayaにはありますよね、たしか。でも、3dsMaxには見当たらない。もしかしたらどこかにあるのかな・・・・・・。(いままで3dsMaxで使おうと思ったことがないというのもありますが)<span>よくわかりません。</span></p>
</ul>
<p>僕は、<span>スポットライトとオムニライトぐらいしか使いません。</span>けれども、その使っている2つのライトについてわかっているわけではなくて、それ以外のものが全然わからなさすぎて、その2つを使っているというのが実際のところ(笑。</p>
<p>そういったことがあって、その2つのライトをどういった感じで使っていくのか。そのことに力を入れていこうかな、と思いました。</p>
<h4>三点照明</h4>
<p>影がくっきりしていると、それは見ている人に硬い印象を与え、柔らかい印象を与えたければぼんやりとしたものにする。そういった影の表現をするための考えとして、三点照明があげられます。照明の世界では基本的な概念のようです。</p>
<p>その三点照明というのは名前のとおりに３つの照明を使います。そして、その３つの照明は、各々の役割が決まっています。</p>
<ul>
<li>キーライト</li>
<p>被写体を一番強く照らす、ライト照明のキーとなる軸を決める役割のライトのこと。<br /><span>このライトの位置がカメラに近寄りすぎてしまうと、物体の形状が平坦に見えます。</span></p>
<li>フィルライト</li>
<p>キーライトが照らすことのできなかった(暗い)部分や、やんわりとした光を被写体に与える役割を持つライトのこと。(色味を加えたりするときにも用いる・・・・・・かな。)</p>
<p>ちなみに、フィルライトが明るすぎると、被写体が平坦に見えてしまうし、フィルライトが暗すぎると、これまた被写体が平坦に見えてしまう。そのため、キーツーフィル比というのを考える必要があります。</p>
<li>バックライト</li>
<p>被写体の後ろに置き、カメラに向けて投射するライトのこと。主に被写体の輪郭を背景から浮き出たせるために用います。(CGの場合は、バックライトというよりリアライト・・・・・・？)</p>
</ul>
<h4>キーツーフィル比</h4>
<p>キーライトとフィルライトの比率のことです。たとえば、フィルライトを基準に考えて、キーライトがフィルライトの2倍の明るさを持っていたら、2：1といった感じに表現します。僕はこの比率を3：1か4：1ぐらいを目安に最初はフィルライトを用意しています。</p>
<p>この比率は、コントラストについて考えることに繋がります。薄暗い場面を作るときにはコントラストを強くすることがあると思いますが、この比率を10：1 (ちょっと無責任な数字を例にします) とか高いキーツーフィル比にすると、明るい部分と暗い部分の差がはっきりして、それっぽく見えます。</p>
<p>逆に、2:1 とか低いキーツーフィル比はキッチンとか反射が多く生じるような場所で使います。</p>
