#+TITLE: "2009年のアクセス数"
#+DATE: 2009-12-31T12:26:23+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

2009年のこのブログへのアクセス総数はどうだったのかを調べました。
今回調べたことは以下の通りです。アクセス解析は<a href="http://research-artisan.com/" target="_blank">リサーチアルチザン</a>を利用しています。
<ul>
	<li><a href="#01">アクセス数</a></li>
	<li><a href="#02">検索ワード</a></li>
	<li><a href="#03">ブラウザ利用割合</a></li>
	<li><a href="#04">OS利用割合</a></li>
</ul>
<h4><a name="01">アクセス数</a></h4>
さて、気になる数字ですが調べてみると以下の通りでした。
<ul>
	<li>ユニークアクセス総数:24,180</li>
	<li>アクセス総数:38,740</li>
</ul>
結構観てくださる方がいます。みなさん、ありがとうございます。この結果には自分自身驚きです。
来年はもっとアクセス数を伸ばしていこうと思います。目標に5万件と置きたいですね。
<h4><a name="02">検索ワード</a></h4>
このブログに来る方は、Ubuntu, インストール, VMWare, Firefox, Liquidなどのキーワードで検索されるみたいです。特にUbuntuは圧倒的に多く、全体の4割を占めています。

あとシュークリームと入れて検索される方もそれなりにいるみたいです。ですが、こちらに関してはそんな面白いものないです。そのうち、何かちゃんと書こうとは思っていますけれどもいつになるかわかりません。
<h4><a name="03">ブラウザ利用割合</a></h4>
このブログを閲覧する際に利用しているブラウザを第5位まで調べました。結果は以下の通りでした。
<ul>
	<li>43%: Mozilla Firefox</li>
	<li>15%: InternetExplore 8</li>
	<li>12%: InternetExplore 6</li>
	<li>10%: Google Chrome</li>
	<li>09%: Safari</li>
	<li>11%: その他</li>
</ul>
Firefoxユーザが最も多く、続いてIEユーザー。その後に続くのがWebKit勢(ChromeとSafari)ですね。IE8ならばレイアウト崩れがそれほどないと思います。<span style="color: #800000;">ただ、IE6で観た場合は相当崩れていると思うのですがどうなんでしょうか。<span style="color: #000000;">ちょっとだけその辺りが気になりますね。</span></span>

ちなみに、それより下には次のブラウザを利用する方もいることがわかりました。NetScapeを使っている方がいることにとても驚きました。また、PlayStationでもアクセスしている方がいるんですね、これもまた驚きです。それからiPhone以外の端末、特にiMode(携帯端末)には適応化させるつもりはありません。(ちかくにパケ放題の携帯があれば別なんですが)
<ul>
	<li>iMode</li>
	<li>NetScape7.x</li>
	<li>PlayStation</li>
</ul>
<h4><a name="04">OS利用割合</a></h4>
どのOSを使っているのかも調べました。結果は以下の通りです。
<ul>
	<li>44%: Windows XP</li>
	<li>16%: Linux</li>
	<li>15%: Mac OS X</li>
	<li>12%: iPhone</li>
	<li>13%: その他</li>
</ul>
言うまでもなくWindowsが圧倒的に多いです。
2位に続くのはLinuxユーザーとなっています。これはUbuntu等の記事を書いているからですかね。
3位にMacユーザーがいます。2位と3位は僅差です。来年はどうなっているのかちょっと楽しみです。
