#+title: ニューヨークタイムズと日本ゲーム市場
#+date: 2010-10-27T00:16:26+09:00
#+draft: false
#+tags: 過去記事インポート

今年の9月19日に電子版のニューヨークタイムズが面白い記事を載せていました。この日は東京ゲームショウが開かれていて、記事の中には現地でのインタビューもあるのですが、テレビゲーム市場の世界シェアの推移に関する記述が興味深い。<!--more--><blockquote>Global sales numbers for the entire industry are hard to come by. But Japan’s share of the world’s video game market, both hardware and software, has fallen to slightly more than 10 percent in 2009, from estimates as high as 50 percent in 2002, based on figures from the Entertainment Software Association, the Japan External Trade Organization, and the research companies DFC Intelligence and Enterbrain.<p style="text-align:right;"><a href="http://www.nytimes.com/2010/09/20/technology/20game.html?_r=1">The New York Times - Japanese Playing a New Video Game: Catch-Up -</a></p></blockquote>日本は2002年では50%ものテレビゲーム市場でのシェアを持っていたが2009年には10%へと減少しているそうです。さらに記事の続きを読むと、2009年の日本のゲーム市場規模が6.4億ドルに対し、米国のゲーム市場は19.7億ドルへと成長していることがわかります。市場規模にこのような変化が現れたためか、挙句の果てには「同じようなことを繰り返しているだけ」とか、こんなすごいことを言われてしまう。<blockquote>“Japan used to define gaming,” said Jake Kazdal, a longtime developer who has worked at Sega in Tokyo and the American game publisher?<a title="More information about Electronic Arts Inc" href="http://topics.nytimes.com/top/news/business/companies/electronic_arts_inc/index.html?inline=nyt-org">Electronic Arts</a>. “But now many developers just do the same thing over and over again.”<p style="text-align:right;"><a href="http://www.nytimes.com/2010/09/20/technology/20game.html?_r=1">The New York Times - Japanese Playing a New Video Game: Catch-Up -</a></p></blockquote>この手の記事はよく調べてみないと間違ってはいないが正しくなくはない記事というのが常だと思うけれど、僕の中で「がんばれ、日本」ではなく「諦めろ、日本」という考えを思わせる記事でした。「諦めろ、日本」
