#+title: NEX-5用のレンズ
#+date: 2010-11-03T11:10:36+09:00
#+draft: false
#+tags: 過去記事インポート

<p>最近、時間があるときにはカメラレンズを調べています。正直なところ、よくわからないのだけれども、今年に買ったソニー製のミラーレスカメラ"NEX-5"にどんなレンズを着けようかと夢を膨らますのは非常に楽しいです。</p><!--more--><p>この手のカメラの魅力はレンズ交換にあると思いますが、NEX-5のレンズマウント(カメラ本体とレンズが接続する箇所)はソニーの新規格である"Eマウント"のため形状が合わず、従来のレンズが残念なことに使えないのです。また、現在でEマウントに対応しているレンズは数種のみでレンズ交換を楽しむにはいささか難ありです。ただ、マウント規格が違うレンズは変換器であるマウントアダプターを装着すればマウント可能なので、NEX-5のものがあれば無事に問題は解決へと向かうのですがソニーが出しているのはαマウント用マウントアダプターのみです。そのため、例えばNikkon用のレンズを持っていても使えません。</p><ul>	<li>Nikkon → Fマウント</li>	<li>Canon → EFマウント</li>	<li>PENTAX → Kマウント</li>	<li>OLYMPUS → OMマウント</li>	<li>Sony → αマウント</li></ul><p>インターネットで調べると、NF-SαEというマウントアダプターでニコン用レンズが使用できるという記事がいくつかあります。その他、ペンタックス用のマウントアダプターもあるそうですが、実際に目で見てないので本当なのか疑問を抱いてしまいます。NF-SαEを作っている<a href="http://homepage2.nifty.com/rayqual/index.htm">宮本製作所</a>に連絡とってみるのが一番良さそう。</p><ul>	<li><a href="http://hairman.moe-nifty.com/aoirogingadan/2010/08/n-5df3.html">SONY NEX-5 で写真④ Planar T* 1.4/50 ZF</a></li>	<li><a href="http://la-diable.blog.so-net.ne.jp/2010-09-22">NEX-5　+　ZEISS　PLANAR T* 1.4/50MM ZF.2</a></li>	<li><a href="http://sudoko.jp/photo/1690/0522/">NEX-5でニッコールを </a></li>	<li><a href="http://sudoko.jp/photo/1690/0522/">使うのは、もちろん夢ではないのです</a>。</li>	<li><a href="http://backyardbuilt.blog118.fc2.com/blog-entry-272.html">Rayqualのマウントアダプター NFG-SαE</a></li>	<li><a href="http://jibunbox.blog64.fc2.com/blog-entry-1456.html#comment2118">マウントアダプタが届いたのでテスト</a></li>	<li><a href="http://marumasa2001.web.infoseek.co.jp/photo/camera/NEX5/adapter/adapter.htm">SONY NEX-5 ペンタックスレンズ用アダプタ</a></li></ul><p>NEX-5にカメラレンズ <a href="http://www.cosina.co.jp/seihin/cz/zf-50/index.html">Planar T* 1.4/50 ZF</a> か、羨ましい。</p>
