#+TITLE: Mac OS X Snow Leopard でディスクイメージを作成する
#+DATE: 2010-04-11T11:29:28+09:00
#+DRAFT: false
#+TAGS: 過去記事インポート

Mac OS X Snow Leopard のインストールメディアを使用することで, 現状の Mac を再現するディスクイメージが作成できる. ディスクイメージさえあれば, その状況に戻す "復元" が可能だ. 復元では, 好きな状況の Mac を他のハードディスクに移すこともできる.

これによって, Final Cut Studio などをすべてインストールして何時間もかかるソフトウェアであっても, その状態に費やす時間を30分から40分前後に短縮することができる.
<h3>ディスクイメージの作成とその保存</h3>
ディスクイメージの作成はとても簡単だ. ディスクイメージは下記の方法で作成できる.
<ol>
	<li> Mac OS X Snow Leopard インストールメディアを Mac に挿入したまま起動する.</li>
	<li>起動したら, インストールメディアで使用する言語を選択する.</li>
	<li>上部メニューにある ユーティリティ を選択し, そこで表示できる ディスクユーティリティ を選択する.</li>
	<li>ディスクユーティリティが起動したら, 上部メニューにある ファイル &gt; 新規 &gt; "" からのディスクイメージ を選択する.</li>
</ol>
<h3>復元方法</h3>
ディスクユーティリティ を使う. これはインストールメディアから起動することで使える.
<ol>
	<li>イメージ &gt; 復元するイメージをスキャン</li>
	<li>"復元" タブを選択する (近くには "First Aid", "消去", "RAID" タブがある).</li>
	<li>"ソース" には "イメージ" ボタンからディスクイメージファイルを選択する.</li>
	<li>"復元先" には ウィンドウの左側にある HDD のリストから受け皿として使用するものをドラッグ＆ドロップする.</li>
	<li>"復元" ボタンを押す.</li>
</ol>
30分から40分ぐらいかかってしまうが, Mac OS X をインストールした後に, Final Cut Studio をインストールするといった形を何度も踏まずにすむ. それも とても簡単に早くことがすむ.

これ以外にも, システムプロファイラは確実に入手しておく. こうすれば, 復元しなくとも対象の Mac がどういった状態なのかを知ることができ, 最低限の情報は確保できていることになる. 別途,  その中から必要な情報を抽出しておくことが望ましい.
