#+title: Google Apps と iPhone の同期設定方法
#+date: 2010-10-31T21:21:46+09:00
#+draft: false
#+tags: 過去記事インポート

<p>iPhone と Google カレンダー?や?Gmail?を同期させて使用している方は多いと思います。設定方法に関して、ウェブ上でGoogle カレンダーに限定して探しても次のような記事がたくさん見つかります。</p><blockquote><a href="http://www.google.com/support/mobile/bin/answer.py?answer=138740&amp;topic=14252">iPhone や iPod touch で Google Sync をセットアップする</a> by <a href="http://www.google.co.jp/">Google</a><a href="http://www.appbank.net/2009/06/24/iphone-news/33309.php">iPhone標準のカレンダーとgoogleカレンダーを同期させる一番便利で簡単な方法</a> by <a href="http://www.appbank.net">AppBank</a><a href="http://ascii.jp/elem/000/000/212/212557/">iPhoneとカレンダーを同期　Google Syncを試す</a> by <a href="http://ascii.jp/mac/">ASCII.jp</a><a href="http://dekiru.impress.co.jp/contents/040/04002.htm">iPhoneでGoogle　カレンダーを同期させる設定方法は？</a> by <a href="http://dekiru.impress.co.jp">できるネット＋（できるネットプラス）</a></blockquote><!--more--><p>一方、所有しているドメインを利用してメールやカレンダーが使える<a href="http://www.google.com/apps/intl/ja/business/index.html">Google Apps</a> と iPhone との同期設定方法についてウェブ上で探しても以下に挙げる数点のみです。(残念なことに画像があまりに多過ぎて分かりづらい)</p><blockquote><a href="http://blog.the-super-suits-store.com/Nakama/?p=196">google sync でメール同期対応。 googleAppsも可</a> by <a href="http://blog.the-super-suits-store.com"> ザ・スーパースーツストア　仲間ブログ</a><a href="http://itfun.jp/2009/02/google-apps-google-sync.html">Google Apps でGoogle Syncを利用する。</a> by <a href="http://itfun.jp"> itFun.jp</a><a href="http://journal.mycom.co.jp/series/googleapps/012/index.html">iPhoneで「Googla Apps」を使う</a> by <a href="http://journal.mycom.co.jp">マイコミジャーナル</a></blockquote><p>そこで以下に簡単にまとめました。</p><ol>	<li><strong>Google Appsでの設定</strong><ol>	<li>Google Apps コントロール パネル にログイン</li>	<li>同コントロールパネルの下段にある "モバイル" を選択</li>	<li>"Google Syncを有効にする"?をチェック</li>	<li>"変更を保存する" をクリック</li></ol></li>	<li><strong>iPhone で Microsoft Exchange アカウントの設定</strong><ol>	<li>"設定アイコン" をタップ</li>	<li>"メール連絡先・カレンダー" をタップ</li>	<li>"アカウントを追加"で、"Microsoft Exchange" をタップ</li>	<li>以下に挙げる必須事項を入力</li></ol></li><blockquote>ドメイン　空欄ユーザ名　name@example.comパスワード 上記ユーザのパスワードサーバ　m.google.com</blockquote><p style="margin-left:13px;"><span style="color:#800000;"><strong>※</strong></span>メールの同期設定方法は、iPhone上でいま作成したアカウントのメールをオンに変更するだけ</p>	<li><strong>iPhone から m.google.com へアクセス</strong> (Google Syncへのアクセスです)<ol>	<li>"Google Appsをご利用の場合" をタップし、ドメインを入力</li>	<li>"言語を設定" をタップし、English (UK) ないし English (US) を選択</li>	<li>緑色枠内にある "Sync" をタップ</li>	<li>"Sign in with your Google Apps Account" をタップ</li>	<li>ログインを行う</li>	<li>"iPhone" の欄をタップ</li>	<li>同期したいカレンダーを選択 (<span style="color:#800000;">上限は25個</span>まで)</li>	<li>"Save" をタップ</li></ol></li></ol>
