#+title: 章毎のWord文書ファイル保存のススメ
#+date: 2011-05-22T16:03:33+09:00
#+draft: false
#+tags: 過去記事インポート

<p>多くの企業で文書を作成する際、特別な事がない限りは誰もが真っ先にWordを使う。数ページ程度の書類ならば１人で済むうえにお決まりの事務文書ならテンプレートファイルを使えば良い。ただし、Wordで複数の章で成る数十ページから数百ページに及ぶ文書を作る場合には巧くいかない。いくつかの試練を乗り越える必要がある。その試練の中から今回は次の2点に限定して策を考えたい。</p><ol>	<li>加筆修正をするページへ移動するのに見出しマップを使っても耐え難い苦悩の解決。</li>	<li>文書レイアウトが崩れと同時に文章が消失し、死にものぐるいの書き直し作業の回避。</li></ol><!--more--><p>結論として、これらを解決するためには<strong>章毎にWordファイルを作成しそれらを別のWordファイルにリンクして統合</strong>する。その理由は次の通りだ。</p><ol>	<li>章毎にファイルを分割、修正に関係する部分のみを開く事が可能。ページ移動が楽になる。</li>	<li>統合にはリンクを利用、修正した箇所のみに限定して反映可能。不要な誤修正を防ぐ。</li>	<li>章毎にファイルを分割しているため、レイアウト崩れによる文章の紛失を最低限に回避できる。</li>	<li>Word文書の全渡し、必要な部分に関係するファイルだけに限定して渡すことが可能。</li></ol><p><strong>リンクして統合する方法</strong></p><ol>	<li>上部のメニュー &gt; 挿入 &gt; ファイル を選択。ダイアログウィンドウが出る。</li>	<li>1のウィンドウで 「ファイルをリンク」にチェックを入れ、ファイルを選択する。</li></ol><p><strong>条件</strong></p><ol>	<li>予め段落番号（章番号などに利用）を割り振っておく必要がある。</li></ol><p><strong>課題</strong></p><ol>	<li>リンクにはフルパスを使用する。そのため関連するWord文書の場所を変えた場合フィールドコートのパスを変更する必要がある。</li><blockquote>INCLUDETEXT "Macintosh HD:Users:yourname:Desktop: document1.docx"</blockquote>	<li>PDF出力したすると、そのPDFの目次にはリンクが付かずページジャンプ不可能。</li></ol>
