#+title: パッケージ管理システムMacPortsの導入
#+date: 2012-05-04T10:35:50+09:00
#+draft: false
#+tags: 過去記事インポート

<h2>はじめに</h2><p>この記事では以下に記載する環境にMacPortsを導入する方法を取りあげる。なお、MacPortsについては<a href="http://www.macports.org/" title="The MacPorts Project Official Homepage">The MacPorts Project</a>を参照のこと。</p><h3>環境</h3><ul><li>Mac OS X Lion 10.7.3</li><li>Xcode 4.3.2 (Command Line Toolsをインストール済みであること)</li><li>Subversion 1.6.17</li><li>Zsh 4.3.11 (i386-apple-darwin11.0)</li></ul><p>Xcodeは<a href="http://guide.macports.org/#installing.xcode.lion" title="MacPorts Guide: Install Xcode on Mac OS X 10.7 Lion">MacPorts Guideの2.2.1. Install Xcode on Mac OS X 10.7 Lion</a>に従ってインストールされているものとする。</p><h3>インストール対象</h3><ul><li>MacPorts 2.0.99</li></ul><!--more--><h2>導入手順</h2><h3>1.MacPortsのソースコードを入手</h3><p><a href="https://trac.macports.org/browser" title="MacPorts Repository">MacPortsのTrac source browser</a>で配布しているソースコードを使用する。</p><pre><code>$ cd ~/repository$ mkdir ./macports$ svn checkout http://svn.macports.org/repository/macports/trunk/base ./macports</code></pre><h3>2.MacPortsをコンパイル</h3><p><a href="http://guide.macports.org/#installing.macports.subversion" title="MacPorts Guide: Subversion Install">MacPorts Guideの2.3.3.Subversion Install</a>の2.Build and Install MacPortsに従いコンパイルする。</p><pre><code>$ cd ~/repositroy/macports$ ./configure --enable-readline$ make$ sudo make instal$ make distclean</code></pre><h3>3.MacPortsをパスに追加</h3><p>Zshの設定ファイルに追記する。</p><pre><code>$ vim .zshrcPATH=/opt/local/bin:/opt/local/sbin:$PATHMANPATH=/opt/local/share/man:$MANPATH</code></pre><h3>4.MacPortsを更新</h3><pre><code>$ sudo port selfupdate$ sudo port upgrade outdated</code></pre>
