#+title: 軽量マークアップ言語Markdownの導入
#+date: 2012-04-30T14:55:58+09:00
#+draft: false
#+tags: 過去記事インポート

<h2>はじめに</h2><p>この記事は以下に記載する環境に2つのファイルをインストールすることでMarkdownを導入できる方法を取りあげる。なお、Markdownについては <a href="http://daringfireball.net/projects/markdown/" title="Daring Fireball: Markdown">Daring Fireball: Markdown</a>か<a href="http://ja.wikipedia.org/wiki/Markdown">WikipediaのMarkdown</a>を参照のこと。</p><h3>環境</h3><ul><li>Mac OS X Lion 10.7.3</li><li>Emacs 23.4(9.0)</li></ul><h3>インストールするファイル</h3><ol><li>Markdown.plの導入</li><li>Markdown-mode.elの導入</li></ol><!--more--><h2>インストール</h2><h3>1. Markdown.plの導入</h3><p>使用するバージョンは1.0.1とする。</p><p>1.1 Markdown.plの入手と設置</p><pre><code>$ cd ~/$ wget http://daringfireball.net/projects/downloads/Markdown_1.0.1.zip$ unzip Markdown_1.0.1.zip$ sudo cp Markdown_1.0.1/Markdown.pl /usr/local/bin/markdown$ ls /usr/local/bindrwxr-xr-x	5 root	admin	  170  4 30 12:53 .drwxr-xr-x	 6 root	 admin	   204	4 30 23:07 ..-rwxr-xr-x@ 1 root  admin   35622  4 30 12:30 markdown</code></pre><p>1-2. 環境変数(パス)の確認</p><p>whichコマンドを使い、パスが通っているか確認する。パスが返ってきたら成功とする。万が一、期待する動作にならない場合はシェルの設定ファイルのパスに関する記述を見直すか、自力で対処法を見つけてほしい。</p><pre><code>$ which markdown</code></pre><p>1-3. 動作確認</p><p>解凍したZipファイルの中にMarkdown形式で記述されているファイルがある。そのファイルを使ってHTMLファイルが作成できるか確認する。万が一、期待する動作にならない場合は自力で対処法を見つけてほしい。</p><pre><code>$ cd ~/Markdown_1.0.1$ markdown Markdown Readme.text &gt; README.html$ open README.html</code></pre><h3>2. markdown-mode.elの導入</h3><p>gitで配布しているものを使用する。使用するものはコミット番号c3f86536a33ae30263cb7dccd049758939e45082である。 </p><p>2.1 markdown-mode.elの入手と設置</p><pre><code>$ cd ~/repository$ git clone git://jblevins.org/git/markdown-mode.git$ ln -s ~/markdown-mode/markdown-mode.el ~/.emacs.d/lisp/markdown-mode.el</code></pre><p>2.2 init.elの編集</p><pre><code>(add-to-list 'load-path "~/.emacs.d/lisp") ;; パス設定(autoload 'markdown-mode "markdown-mode")	 ;; モード名の定義(setq auto-mode-alist (cons '("\\.md" . markdown-mode) auto-mode-alist))　;; markdownのファイル拡張子の定義(setq markdown-command-needs-filename t)   ;; プレビュー時に日本語が消えるのを回避</code></pre><h3>3. 使い方</h3><ul><li><a href="http://blog.s-amemiya.com/development/emacsのmarkdown-modeを使ってみる/#comment-18">フクロウの雪かき (beta): Emacsのmarkdown-modeを使ってみる</a></li><li><a href="http://blog.2310.net/archives/6">blog::2310: Markdown文法の全訳</a> </li></ul><h3>4. 参考資料</h3><ul><li><a href="http://daringfireball.net/projects/markdown/" title="Daring Fireball: Markdown">Daring Fireball: Markdown</a></li><li><a href="http://jblevins.org/projects/markdown-mode/" title="Emacs Markdown Mode">Emacs Markdown Mode</a></li><li><a href="http://ja.wikipedia.org/wiki/Markdown">Wikipedia: Markdown</a></li><li><a href="http://d.hatena.ne.jp/shokai/20100608/1275998764" title="橋本詳解: markdownインストール">橋本詳解: markdownインストール</a></li><li><a href="http://hico-horiuchi.com/wiki/doku.php?id=emacs:markdown" title="12FF5B8 Wiki: markdown-modeの導入">12FF5B8 Wiki: markdown-modeの導入</a></li><li><a href="http://blog.s-amemiya.com/development/emacsのmarkdown-modeを使ってみる/#comment-18">フクロウの雪かき (beta): Emacsのmarkdown-modeを使ってみる</a></li><li><a href="http://blog.2310.net/archives/6">blog::2310: Markdown文法の全訳</a></li></ul>
