#+title: iPhotoがインストールできない
#+date: 2015-02-11T13:38:18+09:00
#+draft: false
#+tags: 過去記事インポート

今の時代、スマートフォンの普及もあって、写真を撮るのは簡単になった。データをPCへコピーするのも簡単になった。しかしながら、PCでの写真管理は未だに面倒くさいままだ。自分にマッチしたソフトウェアはないか探しまわっている人も多いのではないか。

私は写真管理にiPhotoを使っている。似たようなアプリケーションにAdobeが出しているBridgeやElements Organizerがあるが、これらとは異なる要素を持っているiPhotoへ移った。きっかけは[MacBook Air (11-inch, Mid 2011)](http://support.apple.com/kb/SP631?viewlocale=ja_JP)にプリインストールされていたものを使ったこと。今ではもう4年近くの付き合いで、iPhotoがないと写真管理が億劫だ。

## iPhotoの販売チャネル

さて、私とiPhotoの付き合いついて述べたところでチャネルについて触れたい。私はiPhotoをプリインストールという形で入手したが、それ以外のルートではMac App Storeで購入する必要があった。私の記憶では価格は1500円だった。

Mac App Storeで購入すれば、その情報がApple IDに紐づくので、アプリのアップデート、再インストールは同ストアから行える。しかし、プリインストールのiPhotoユーザの場合はこの紐づけが出来ていないためか「受け取り」手続きをする必要があった。

iPhotoのメジャーアップデートがかかり、新しいバージョンはMac OS X Yosemite以上でなければインストールできないことになった。Mac App Storeはちょっと面白いので、同名アプリ(というよりはID)のアップデートにOSのサポート範囲の変更があると、購入したはずの製品が非表示になるという現象が発生する。これが発生するとエンドユーザは「買ったアプリが消えた!」と騒ぐ。かくいう私もその一人であった。

チャネルとしてどうなのだろうと思うが、アプリの流通プラットフォームは「新しいアプリに更新させる」が重要なタスクなので、間違っているとは言えない。

## iPhotoを取り戻す

似たような状況に陥る人はいるようで、下記で情報交換がされていた。

- [過去に購入したiPhotoをAppStoreからインストールしようとすると有料表示 | Apple サポートコミュニティ](https://discussionsjapan.apple.com/message/100842126#100842126)

どうやら「購入したアプリは非表示になっているだけで、表示すれば良い」という話のようだ。

手順は以下の通り。

1. AppStoreを起動する
2. 上部メニューのStoreから「マイアカントを表示」をクリック
3. ログインフォームでアカウント情報を入力。「アカウント表示」をクリック
4. 非表示の購入済みアイテムでiPhotoがあれば、その行の右端にある「表示する」ボタンをクリック
5. 購入済みに移動すると、iPhotoが表示されている。あとはいつも通りインストールするだけ

## 余談

写真加工をしようとして、Photoshop Elements 9をインストールしたが、Mac OS X 10.9では起動しなかった。Elements Organizerも挙動が不安定であった。Adobeのナレッジベースを漁ってみたところ、Mac OS X 10.9は動作保障外のようだ。

- [旧バージョンの対応 OS： Photoshop Elements](https://helpx.adobe.com/jp/photoshop-elements/kb/5127.html)

こういった記事も見つかった。

- [Mavericks再インストール - N@i Blog](http://y-naito.ddo.jp/index.php?id=1390724413)
