#+TITLE: Rで統計学入門 記録3
#+AUTHOR: Hiroaki ENDOH
#+DATE: 2018-03-17
#+DRAFT: false
#+TAGS: 統計学 R

* はじめに

前回は以下の学習をしました。

- 相関係数

今回は統計学入門の 2.2 代表値で挙げられている以下の平均について学習します。

- 算術平均
- 幾何平均
- 調和平均

* 算術平均

算術平均は相加平均とも呼ばれます。<br/>
観測値が連続的なデータ (例: 試験の得点) の場合に使います。<br/>
下記の数式で\(\overline{x}\) (エックスバー) を求めます。

\[
  \overline{x} = \frac{x_1 + x_2 + \cdots + x_n}{n}
\]

あるいは、このように表すと便利かもしれません。

\[
  \overline{x} = \frac{1}{n} \sum_{i=1}^n x_i
\]

算術平均は全てのデータを考慮できる反面、外れ値（異常に大きい値，小さい値）に弱いことが挙げられます。

** 例題1 国語テストの点数

#+BEGIN_QUOTE
六人の国語のテストの点数はそれぞれ 52,52,70,72,80,100 点であった。テストの点数の平均を求めよ。

平均値，中央値，最頻値の求め方といくつかの例 | 高校数学の美しい物語
https://mathtrain.jp/daihyochi
#+END_QUOTE

これを先述の数式に当てはめると以下になります。

\[
  \overline{x} = \frac{52 + 52 + 70 + 72 + 80 + 100}{6} = \frac{426}{6} = 71  
\]

Rでやってみると、こうなります。

#+BEGIN_SRC r
# コード
x <- c(52,52,70,72,80,100)
mean(x)

# 結果
> x <- c(52,52,70,72,80,100)
> mean(x)
[1] 71
#+END_SRC

** 例題2 数学テストの点数

#+BEGIN_QUOTE
数学のテスト直前に天才が転校して来た。数学のテストはとても難しかった。その結果，七人の数学のテストの点数はそれぞれ 6,9,9,10,10,10,100 点であった。テストの点数の平均を求めよ。

平均値，中央値，最頻値の求め方といくつかの例 | 高校数学の美しい物語
https://mathtrain.jp/daihyochi
#+END_QUOTE

式に当てはまると次になります。

\[
  \overline{x} = \frac{6 + 9 + 9 + 10 + 10 + 10 + 100}{7} = \frac{154}{7} = 22  
\]

ほとんどが10点なのに、1人が100点のため、平均値があがっています。<br/>
外れ値の影響を受けていることが伺えます。

Rでやってみると、こうなります。

#+BEGIN_SRC r
# コード
x <- c(6,9,9,10,10,10,100)
mean(x)

# 結果
> x <- c(6,9,9,10,10,10,100)
> mean(x)
[1] 22
#+END_SRC

* 幾何平均

幾何平均は相乗平均とも呼ばれます。<br/>
預金の利子などの変量の平均を求める場合に用います。

\[
  {x_G} =\sqrt[n]{x_1 \times x_2 \times \dotsb \times x_n}
\]

** 例題1 伸び率の計算

#+BEGIN_QUOTE
100 円だった物の価値が、1年目は 2 ％上がった。2年目は 18 ％上がった。この物の価値は年間平均何％上がったと言えるか？

相乗平均の意味、図形的イメージ、活躍する例 - 具体例で学ぶ数学
https://mathwords.net/soujouheikin
#+END_QUOTE

\[
  {x_G} = \sqrt{1.02 \times 1.18} = 1.097087052152198
\]

Rでやってみると、こうなります。

#+BEGIN_SRC r
# コード
x <- c(1.02, 1.18)
prod(x)^(1/length(x))

# 結果
> x <- c(1.02, 1.18)
> prod(x)^(1/length(x))
[1] 1.09708
#+END_SRC

* 調和平均

逆数どうしの算術平均です。<br/>
ある一定量の値に対して、単位当たりの平均を求める場合に使います。

\[
  \frac{1}{x_H} = \frac{1}{n} (\frac{1}{x_1} + \cdots + \frac{1}{x_n})
\]

あるいは、このように表すと便利かもしれません。

\[
  \frac{1}{x_H} = \sum_{i=1}^n \frac{1}{x_i}
\]

** 例題1 バスの平均速度

#+BEGIN_QUOTE
ある路線バス行きは時速25km、帰りは時速15kmで往復した時の平均速度を求めよ。

統計学入門 P31
#+END_QUOTE

計算するにあたって、以下の通りとします。

- 平均速度を\(v\)
- 距離を\(d\)
- 行きにかかった時間を \(\frac{d}{25}\)
- 帰りにかかった時間を \(\frac{d}{15}\)

往復にかかった時間を以下の数式で表します。

\[
\begin{eqnarray}
  \frac{1}{v} 
  & = & \frac{1}{2d} (\frac{d}{25} + \frac{d}{15}) \\
  & = & \frac{1}{2d} (\frac{25d + 15d}{25 \times 15}) \\
  & = & \frac{1}{2d} (\frac{40d}{375}) \\
  & = & \frac{40d}{750d} \\
\end{eqnarray}
\]

逆数をかけると、平均速度がわかります。

\[
\begin{eqnarray}
  v 
  & = & \frac{750d}{40d}
  & = & 18.75 km/h
\end{eqnarray}
\]

Rでやってみると、こうなります。

#+BEGIN_SRC r
# コード
x <- c(25, 15)
1/sum(1/x)*length(x)

# 結果
> x <- c(25, 15)
> 1/sum(1/x)*length(x)
[1] 18.75
#+END_SRC

** 例題2 商品の平均金額

#+BEGIN_QUOTE
A君とB君が500円ずつお小遣いを持って、お菓子を買いに言ったとします。A君は100円のお菓子を5個、B君は20円のガムを25個買ったとします。A君とB君が購入したすべての商品1個あたりの平均金額はいくらでしょうか？

[ 中学数学・理科 ] 調和平均の考え方（速さから合成抵抗まで） – 行け！偏差値40プログラマー
http://hensa40.cutegirl.jp/archives/333
#+END_QUOTE

\[
\begin{eqnarray}
  \frac{1}{H} 
  & = & \frac{1}{2} (\frac{1}{100} + \frac{1}{20}) \\
  & = & \frac{1}{2} (\frac{2}{200} + \frac{10}{200}) \\
  & = & \frac{1}{2} (\frac{12}{200}) \\
  & = & \frac{6}{200} \\
\end{eqnarray}
\]

\[
\begin{eqnarray}
  H
  & = & \frac{200}{6}
  & = & 33.3 yen
\end{eqnarray}
\]

Rでやってみると、こうなります。

#+BEGIN_SRC r
# コード
x <- c(100, 20)
1/sum(1/x)*length(x)

# 結果
> x <- c(100, 20)
> 1/sum(1/x)*length(x)
[1] 33.33333
#+END_SRC
* まとめ

この記事では以下のことを学習しました。

- 算術平均
- 幾何平均
- 調和平均

次回は以下について学習したいと思います。

- メディアン
- モード
